// Package openapi embeds the bundled OpenAPI description of the Meridian Plugin
// API (openapi.json, built by bundle.py from openapi.yaml + paths/ + schemas/)
// and lets a plugin or a host validate methods and messages against it. The
// Go wire types of the same document are the parent package, pluginshttp,
// generated by `bifrost-prep genspec`.
//
// One operation per hook (POST /api/meridian/plugin/v1/{method}), the
// lifecycle and probe operations, one schema per message, and the HookStream
// envelope for the WebSocket transport.
package openapi

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"strings"
	"sync"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

//go:embed openapi.json
var bundled []byte

// BasePath prefixes every operation path.
const BasePath = "/api/meridian/plugin/v1"

// HookStreamMethod is the operationId of the WebSocket upgrade endpoint.
const HookStreamMethod = "HookStream"

// LifecycleMethods are the operations every plugin must serve regardless of
// which hooks it implements.
var LifecycleMethods = []string{"Capabilities", "Init", "GetName", "Cleanup"}

// ProbeMethods are the GET operations a host may call to watch a plugin; a
// plugin may leave them unimplemented (404).
var ProbeMethods = []string{"Health", "Status"}

// Spec returns the bundled OpenAPI document (JSON).
func Spec() []byte { return bundled }

// Operation is one RPC as described by the document.
type Operation struct {
	Method         string // operationId (= gRPC method name)
	Path           string
	HTTPMethod     string
	RequestSchema  string // component schema name of the request body ("" for HookStream)
	ResponseSchema string // component schema name of the 200 response ("" for HookStream)
}

// Document is the parsed, validated spec.
type Document struct {
	raw        map[string]any
	operations map[string]Operation
	schemas    map[string]*jsonschema.Schema
	compiler   *jsonschema.Compiler
	mu         sync.Mutex
}

var (
	loadOnce sync.Once
	loaded   *Document
	loadErr  error
)

// Load parses the embedded document once.
func Load() (*Document, error) {
	loadOnce.Do(func() { loaded, loadErr = Parse(bundled) })
	return loaded, loadErr
}

// MustLoad is Load that panics on error (the embedded document is validated by tests).
func MustLoad() *Document {
	d, err := Load()
	if err != nil {
		panic(err)
	}
	return d
}

// Parse parses an OpenAPI 3.1 JSON document and prepares the schema compiler.
func Parse(data []byte) (*Document, error) {
	v, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("openapi: parse: %w", err)
	}
	raw, ok := v.(map[string]any)
	if !ok {
		return nil, errors.New("openapi: document is not an object")
	}
	if ver, _ := raw["openapi"].(string); !strings.HasPrefix(ver, "3.1") {
		return nil, fmt.Errorf("openapi: unsupported version %q (want 3.1.x)", raw["openapi"])
	}
	d := &Document{raw: raw, operations: map[string]Operation{}, schemas: map[string]*jsonschema.Schema{}}
	c := jsonschema.NewCompiler()
	c.DefaultDraft(jsonschema.Draft2020)
	if err := c.AddResource("openapi.json", v); err != nil {
		return nil, fmt.Errorf("openapi: register document: %w", err)
	}
	d.compiler = c

	paths, _ := raw["paths"].(map[string]any)
	for p, item := range paths {
		pi, _ := item.(map[string]any)
		for httpMethod, opv := range pi {
			op, ok := opv.(map[string]any)
			if !ok {
				continue
			}
			id, _ := op["operationId"].(string)
			if id == "" {
				return nil, fmt.Errorf("openapi: %s %s has no operationId", httpMethod, p)
			}
			o := Operation{Method: id, Path: p, HTTPMethod: strings.ToUpper(httpMethod)}
			o.RequestSchema = schemaNameOf(dig(op, "requestBody", "content", "application/json", "schema"))
			o.ResponseSchema = schemaNameOf(dig(op, "responses", "200", "content", "application/json", "schema"))
			d.operations[id] = o
		}
	}
	return d, nil
}

func dig(m map[string]any, keys ...string) map[string]any {
	cur := m
	for _, k := range keys {
		next, ok := cur[k].(map[string]any)
		if !ok {
			return nil
		}
		cur = next
	}
	return cur
}

func schemaNameOf(schema map[string]any) string {
	if schema == nil {
		return ""
	}
	ref, _ := schema["$ref"].(string)
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(ref, prefix) {
		return strings.TrimPrefix(ref, prefix)
	}
	return ""
}

// Operations returns every operation keyed by method name.
func (d *Document) Operations() map[string]Operation {
	out := make(map[string]Operation, len(d.operations))
	for k, v := range d.operations {
		out[k] = v
	}
	return out
}

// Methods returns the sorted operation ids.
func (d *Document) Methods() []string {
	out := make([]string, 0, len(d.operations))
	for k := range d.operations {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// SchemaNames returns the sorted component schema names.
func (d *Document) SchemaNames() []string {
	comps := dig(d.raw, "components", "schemas")
	out := make([]string, 0, len(comps))
	for k := range comps {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// SchemaProperties returns the declared property names of a component schema.
func (d *Document) SchemaProperties(name string) ([]string, bool) {
	s := dig(d.raw, "components", "schemas", name)
	if s == nil {
		return nil, false
	}
	props := dig(s, "properties")
	out := make([]string, 0, len(props))
	for k := range props {
		out = append(out, k)
	}
	sort.Strings(out)
	return out, true
}

// Schema compiles (once) and returns the JSON Schema of a component.
func (d *Document) Schema(name string) (*jsonschema.Schema, error) {
	d.mu.Lock()
	defer d.mu.Unlock()
	if s, ok := d.schemas[name]; ok {
		return s, nil
	}
	if dig(d.raw, "components", "schemas", name) == nil {
		return nil, fmt.Errorf("openapi: unknown schema %q", name)
	}
	s, err := d.compiler.Compile("openapi.json#/components/schemas/" + name)
	if err != nil {
		return nil, fmt.Errorf("openapi: compile %s: %w", name, err)
	}
	d.schemas[name] = s
	return s, nil
}

// Validate checks a Go value (marshalled to JSON) against a component schema.
func (d *Document) Validate(schema string, v any) error {
	s, err := d.Schema(schema)
	if err != nil {
		return err
	}
	data, err := json.Marshal(v)
	if err != nil {
		return fmt.Errorf("openapi: marshal for validation: %w", err)
	}
	return d.validateBytes(s, schema, data)
}

// ValidateJSON checks raw JSON bytes against a component schema.
func (d *Document) ValidateJSON(schema string, data []byte) error {
	s, err := d.Schema(schema)
	if err != nil {
		return err
	}
	return d.validateBytes(s, schema, data)
}

func (d *Document) validateBytes(s *jsonschema.Schema, name string, data []byte) error {
	inst, err := jsonschema.UnmarshalJSON(bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("openapi: %s: invalid JSON: %w", name, err)
	}
	if err := s.Validate(inst); err != nil {
		return fmt.Errorf("openapi: %s: %w", name, err)
	}
	return nil
}

// ValidateRequest validates a request message of the named method.
func (d *Document) ValidateRequest(method string, v any) error {
	op, ok := d.operations[method]
	if !ok {
		return fmt.Errorf("openapi: unknown method %q", method)
	}
	if op.RequestSchema == "" {
		return fmt.Errorf("openapi: method %q has no JSON request body", method)
	}
	return d.Validate(op.RequestSchema, v)
}

// ValidateResponse validates a response message of the named method.
func (d *Document) ValidateResponse(method string, v any) error {
	op, ok := d.operations[method]
	if !ok {
		return fmt.Errorf("openapi: unknown method %q", method)
	}
	if op.ResponseSchema == "" {
		return fmt.Errorf("openapi: method %q has no JSON response body", method)
	}
	return d.Validate(op.ResponseSchema, v)
}

// CheckMethods verifies that every hook a plugin implements is an operation
// of the document (with request and response schemas), and returns the list
// of documented hooks the plugin does not implement (informational). The
// lifecycle operations are mandatory and therefore always counted as
// implemented; they are checked to exist in the document.
func (d *Document) CheckMethods(implemented []string) (missing []string, err error) {
	var errs []error
	seen := map[string]bool{}
	for _, h := range append(append([]string{}, LifecycleMethods...), implemented...) {
		seen[h] = true
		op, ok := d.operations[h]
		if !ok {
			errs = append(errs, fmt.Errorf("hook %q is not an operation of the OpenAPI document", h))
			continue
		}
		if op.RequestSchema == "" || op.ResponseSchema == "" {
			errs = append(errs, fmt.Errorf("operation %q lacks request/response schemas", h))
		}
	}
	for _, m := range d.Methods() {
		if op := d.operations[m]; op.RequestSchema == "" || seen[m] {
			continue // HookStream and the probes carry no request body
		}
		missing = append(missing, m)
	}
	return missing, errors.Join(errs...)
}
