// Code generated by bifrost-prep genspec from framework/pluginshttp/openapi/openapi.json; DO NOT EDIT.

// Package pluginshttp holds the wire types and the operation table of the Meridian Plugin API (version 1.1.0),
// generated from framework/pluginshttp/openapi/openapi.json.
package pluginshttp

import "encoding/json"

// ContextDetails: Wire projection of the host's request context (host -> plugin): request id,
// deadline and the string-valued context entries. The plugin rebuilds a local context from it and
// returns its writes as a ContextDelta.
type ContextDetails struct {
	// Request identifier (also present in ContextDetails.values under the request-id key)
	RequestID string `json:"request_id,omitempty"`
	// Absolute deadline as Unix nanoseconds; 0 = no deadline
	DeadlineUnixNano int64 `json:"deadline_unix_nano,omitempty"`
	// Context values whose key is a BifrostContextKey. Any JSON value (string, number, boolean, array,
	// object); credentials (direct provider key, session token, raw virtual key) never cross.
	Values map[string]json.RawMessage `json:"values,omitempty"`
	// Name of the plugin the context is scoped to
	PluginScope string `json:"plugin_scope,omitempty"`
}

// ContextDelta: Context writes made by the plugin during a call (plugin -> host); the host merges
// them into the real context
type ContextDelta struct {
	// Keys to set (or overwrite); any JSON value. Reserved host keys are dropped by the host.
	Set map[string]json.RawMessage `json:"set,omitempty"`
	// Keys to remove
	Clear []string `json:"clear,omitempty"`
}

// RequestDetails: HTTP transport request envelope: exactly the JSON tags of Meridian's core
// schemas.HTTPRequest (method, path, headers, query, path_params, body) plus host extras. Carried
// by the HTTPTransport* hooks; LLM/MCP hooks carry LLMRequest / MCPRequest instead.
//
// The body appears in exactly one of two forms: `body` (raw JSON, used when the request body is
// valid JSON, copied verbatim) or `body_b64` (base64, used for any other content).
type RequestDetails struct {
	RequestID string `json:"request_id,omitempty"`
	// HTTP method
	Method string `json:"method,omitempty"`
	// URL path
	Path    string            `json:"path,omitempty"`
	Headers map[string]string `json:"headers,omitempty"`
	Query   map[string]string `json:"query,omitempty"`
	// Path variables extracted from the URL pattern
	PathParams map[string]string `json:"path_params,omitempty"`
	// Request body as raw JSON (any JSON value); present only when the body is valid JSON
	Body json.RawMessage `json:"body,omitempty"`
	// Request body, base64-encoded; present only when the body is not valid JSON
	BodyB64 []byte `json:"body_b64,omitempty"`
	// When the host received the request, Unix nanoseconds
	ReceivedAtUnixNano int64  `json:"received_at_unix_nano,omitempty"`
	ClientIP           string `json:"client_ip,omitempty"`
	// Retry/fallback attempt number, 1-based
	Attempt int32 `json:"attempt,omitempty"`
}

// ResponseDetails: HTTP transport response envelope: exactly the JSON tags of Meridian's core
// schemas.HTTPResponse (status_code, headers, body). `body` is raw JSON when the body is valid
// JSON, `body_b64` (base64) otherwise.
type ResponseDetails struct {
	StatusCode int32             `json:"status_code,omitempty"`
	Headers    map[string]string `json:"headers,omitempty"`
	// Response body as raw JSON (any JSON value); present only when the body is valid JSON
	Body json.RawMessage `json:"body,omitempty"`
	// Response body, base64-encoded; present only when the body is not valid JSON
	BodyB64 []byte `json:"body_b64,omitempty"`
}

// StreamChunk: One streamed unit. `chunk` is the JSON of Meridian's core
// schemas.BifrostStreamChunk (its MarshalJSON: the one non-nil embedded stream response for
// `request_type`, or a BifrostError chunk recognisable by `is_bifrost_error`). `index` is
// host-assigned, 0-based, per request.
type StreamChunk struct {
	Index       int64       `json:"index,omitempty"`
	RequestType RequestType `json:"request_type,omitempty"`
	// schemas.BifrostStreamChunk JSON (any JSON value)
	Chunk json.RawMessage `json:"chunk,omitempty"`
}

// BifrostError: Meridian's core schemas.BifrostError with its JSON tags verbatim (event_id, type,
// is_bifrost_error, status_code, error, extra_fields). `allow_fallbacks` and `stream_control` are
// json:"-" in Go and made explicit here because plugins control them. It is data, not a transport
// failure.
type BifrostError struct {
	EventID        string      `json:"event_id,omitempty"`
	Type           string      `json:"type,omitempty"`
	IsBifrostError bool        `json:"is_bifrost_error,omitempty"`
	StatusCode     int32       `json:"status_code,omitempty"`
	Error          *ErrorField `json:"error,omitempty"`
	// schemas.BifrostErrorExtraFields (request_type, provider, model_requested, model_used, ...)
	ExtraFields map[string]json.RawMessage `json:"extra_fields,omitempty"`
	// Boolean; controls fallback behaviour. Absent = the host keeps its own value (default allowed).
	AllowFallbacks json.RawMessage `json:"allow_fallbacks,omitempty"`
	// schemas.StreamControl
	StreamControl map[string]json.RawMessage `json:"stream_control,omitempty"`
}

// ErrorField: schemas.ErrorField JSON tags verbatim
type ErrorField struct {
	Type    string `json:"type,omitempty"`
	Code    string `json:"code,omitempty"`
	Message string `json:"message"`
	// Any JSON value
	Param   json.RawMessage `json:"param,omitempty"`
	EventID string          `json:"event_id,omitempty"`
}

// RequestType: schemas.RequestType; the value names the typed core request/response carried next
// to it
type RequestType string

// Values of RequestType.
const (
	RequestTypeListModels              RequestType = "list_models"
	RequestTypeTextCompletion          RequestType = "text_completion"
	RequestTypeTextCompletionStream    RequestType = "text_completion_stream"
	RequestTypeChatCompletion          RequestType = "chat_completion"
	RequestTypeChatCompletionStream    RequestType = "chat_completion_stream"
	RequestTypeResponses               RequestType = "responses"
	RequestTypeResponsesStream         RequestType = "responses_stream"
	RequestTypeResponsesRetrieve       RequestType = "responses_retrieve"
	RequestTypeResponsesRetrieveStream RequestType = "responses_retrieve_stream"
	RequestTypeResponsesDelete         RequestType = "responses_delete"
	RequestTypeResponsesCancel         RequestType = "responses_cancel"
	RequestTypeResponsesInputItems     RequestType = "responses_input_items"
	RequestTypeEmbedding               RequestType = "embedding"
	RequestTypeSpeech                  RequestType = "speech"
	RequestTypeSpeechStream            RequestType = "speech_stream"
	RequestTypeTranscription           RequestType = "transcription"
	RequestTypeTranscriptionStream     RequestType = "transcription_stream"
	RequestTypeImageGeneration         RequestType = "image_generation"
	RequestTypeImageGenerationStream   RequestType = "image_generation_stream"
	RequestTypeImageEdit               RequestType = "image_edit"
	RequestTypeImageEditStream         RequestType = "image_edit_stream"
	RequestTypeImageVariation          RequestType = "image_variation"
	RequestTypeVideoGeneration         RequestType = "video_generation"
	RequestTypeVideoRetrieve           RequestType = "video_retrieve"
	RequestTypeVideoDownload           RequestType = "video_download"
	RequestTypeVideoDelete             RequestType = "video_delete"
	RequestTypeVideoList               RequestType = "video_list"
	RequestTypeVideoRemix              RequestType = "video_remix"
	RequestTypeBatchCreate             RequestType = "batch_create"
	RequestTypeBatchList               RequestType = "batch_list"
	RequestTypeBatchRetrieve           RequestType = "batch_retrieve"
	RequestTypeBatchCancel             RequestType = "batch_cancel"
	RequestTypeBatchResults            RequestType = "batch_results"
	RequestTypeBatchDelete             RequestType = "batch_delete"
	RequestTypeFileUpload              RequestType = "file_upload"
	RequestTypeFileList                RequestType = "file_list"
	RequestTypeFileRetrieve            RequestType = "file_retrieve"
	RequestTypeFileDelete              RequestType = "file_delete"
	RequestTypeCachedContentCreate     RequestType = "cached_content_create"
	RequestTypeCachedContentList       RequestType = "cached_content_list"
	RequestTypeCachedContentRetrieve   RequestType = "cached_content_retrieve"
	RequestTypeCachedContentUpdate     RequestType = "cached_content_update"
	RequestTypeCachedContentDelete     RequestType = "cached_content_delete"
	RequestTypeFileContent             RequestType = "file_content"
	RequestTypeContainerCreate         RequestType = "container_create"
	RequestTypeContainerList           RequestType = "container_list"
	RequestTypeContainerRetrieve       RequestType = "container_retrieve"
	RequestTypeContainerDelete         RequestType = "container_delete"
	RequestTypeContainerFileCreate     RequestType = "container_file_create"
	RequestTypeContainerFileList       RequestType = "container_file_list"
	RequestTypeContainerFileRetrieve   RequestType = "container_file_retrieve"
	RequestTypeContainerFileContent    RequestType = "container_file_content"
	RequestTypeContainerFileDelete     RequestType = "container_file_delete"
	RequestTypeRerank                  RequestType = "rerank"
	RequestTypeOcr                     RequestType = "ocr"
	RequestTypeCountTokens             RequestType = "count_tokens"
	RequestTypeCompaction              RequestType = "compaction"
	RequestTypeMCPToolExecution        RequestType = "mcp_tool_execution"
	RequestTypePassthrough             RequestType = "passthrough"
	RequestTypePassthroughStream       RequestType = "passthrough_stream"
	RequestTypeUnknown                 RequestType = "unknown"
	RequestTypeWebsocketResponses      RequestType = "websocket_responses"
	RequestTypeRealtime                RequestType = "realtime"
	RequestTypePing                    RequestType = "ping"
	RequestTypeListTools               RequestType = "list_tools"
	RequestTypeChatToolCall            RequestType = "chat_tool_call"
	RequestTypeResponsesToolCall       RequestType = "responses_tool_call"
	RequestTypeExecuteTool             RequestType = "execute_tool"
)

// MCPRequestType: schemas.MCPRequestType
type MCPRequestType string

// Values of MCPRequestType.
const (
	MCPRequestTypePing              MCPRequestType = "ping"
	MCPRequestTypeListTools         MCPRequestType = "list_tools"
	MCPRequestTypeChatToolCall      MCPRequestType = "chat_tool_call"
	MCPRequestTypeResponsesToolCall MCPRequestType = "responses_tool_call"
	MCPRequestTypeExecuteTool       MCPRequestType = "execute_tool"
)

// LLMRequest: An LLM-side request: `request_type` names the typed core request and `request` is
// that struct's own JSON (schemas.BifrostChatRequest for chat_completion(_stream),
// schemas.BifrostEmbeddingRequest for embedding, ...). The untagged union schemas.BifrostRequest
// is never marshalled.
type LLMRequest struct {
	RequestType RequestType `json:"request_type"`
	// JSON of schemas.Bifrost<Type>Request for request_type (any JSON value)
	Request json.RawMessage `json:"request,omitempty"`
}

// LLMResponse: An LLM-side response; `response` is the JSON of schemas.Bifrost<Type>Response for
// `request_type`
type LLMResponse struct {
	RequestType RequestType `json:"request_type,omitempty"`
	// JSON of schemas.Bifrost<Type>Response (any JSON value)
	Response json.RawMessage `json:"response,omitempty"`
}

// LLMShortCircuit: Mirrors schemas.LLMPluginShortCircuit; exactly one of response / error is
// expected
type LLMShortCircuit struct {
	Response *LLMResponse  `json:"response,omitempty"`
	Error    *BifrostError `json:"error,omitempty"`
}

// MCPRequest: An MCP request: the untagged schemas.BifrostMCPRequest crosses as `request_type`,
// `client_name` (snake_case of the Go fields) and `request` = JSON of the typed core MCP request.
type MCPRequest struct {
	RequestType MCPRequestType `json:"request_type"`
	ClientName  string         `json:"client_name"`
	// JSON of the typed schemas.BifrostMCP<Type>Request (any JSON value)
	Request json.RawMessage `json:"request,omitempty"`
}

// MCPResponse: An MCP response; `response` is the JSON of schemas.BifrostMCPResponse
type MCPResponse struct {
	RequestType MCPRequestType `json:"request_type,omitempty"`
	// JSON of schemas.BifrostMCPResponse (any JSON value)
	Response json.RawMessage `json:"response,omitempty"`
}

// MCPShortCircuit: Mirrors schemas.MCPPluginShortCircuit / MCPConnectionShortCircuit
type MCPShortCircuit struct {
	Response *MCPResponse  `json:"response,omitempty"`
	Error    *BifrostError `json:"error,omitempty"`
}

// MCPConnectRequest: schemas.BifrostMCPConnectRequest (untagged in Go; snake_case of the Go field
// names)
type MCPConnectRequest struct {
	ClientName       string            `json:"client_name"`
	ConnectionType   string            `json:"connection_type,omitempty"`
	AuthType         string            `json:"auth_type,omitempty"`
	ConnectionString string            `json:"connection_string,omitempty"`
	Headers          map[string]string `json:"headers,omitempty"`
	// Remaining fields of the Go struct as a JSON object (any JSON value)
	Extra json.RawMessage `json:"extra,omitempty"`
}

// MCPConnectResponse: schemas.BifrostMCPConnectResponse; `response` is its JSON
type MCPConnectResponse struct {
	ClientName string `json:"client_name,omitempty"`
	// JSON of schemas.BifrostMCPConnectResponse (any JSON value)
	Response json.RawMessage `json:"response,omitempty"`
}

// Span: schemas.Span
type Span struct {
	SpanID        string                     `json:"span_id"`
	ParentID      string                     `json:"parent_id,omitempty"`
	TraceID       string                     `json:"trace_id,omitempty"`
	Name          string                     `json:"name"`
	Kind          string                     `json:"kind,omitempty"`
	StartUnixNano int64                      `json:"start_unix_nano,omitempty"`
	EndUnixNano   int64                      `json:"end_unix_nano,omitempty"`
	Status        string                     `json:"status,omitempty"`
	StatusMsg     string                     `json:"status_msg,omitempty"`
	Attributes    map[string]json.RawMessage `json:"attributes,omitempty"`
	Events        []*SpanEvent               `json:"events,omitempty"`
}

// SpanEvent is a message of the document.
type SpanEvent struct {
	Name         string                     `json:"name"`
	TimeUnixNano int64                      `json:"time_unix_nano,omitempty"`
	Attributes   map[string]json.RawMessage `json:"attributes,omitempty"`
}

// PluginLogEntry: schemas.PluginLogEntry
type PluginLogEntry struct {
	Plugin       string `json:"plugin"`
	Level        string `json:"level"`
	Message      string `json:"message"`
	TimeUnixNano int64  `json:"time_unix_nano,omitempty"`
}

// HookError: The Go `error` returned by a hook. Absent means nil. Distinct from transport
// failures.
type HookError struct {
	Message string `json:"message"`
}

// ConfigMap: A plugin configuration object: free-form JSON, passed through unchanged.
type ConfigMap map[string]any

// Trace: schemas.Trace handed to ObservabilityPlugin.Inject (full shape, spans included)
type Trace struct {
	RequestID      string                     `json:"request_id,omitempty"`
	TraceID        string                     `json:"trace_id,omitempty"`
	InternalID     string                     `json:"internal_id,omitempty"`
	ParentID       string                     `json:"parent_id,omitempty"`
	StartUnixNano  int64                      `json:"start_unix_nano,omitempty"`
	EndUnixNano    int64                      `json:"end_unix_nano,omitempty"`
	Attributes     map[string]json.RawMessage `json:"attributes,omitempty"`
	RequestHeaders map[string]string          `json:"request_headers,omitempty"`
	PluginLogs     []*PluginLogEntry          `json:"plugin_logs,omitempty"`
	Spans          []*Span                    `json:"spans,omitempty"`
}

// HookName: Name of a hook (an operation of this document)
type HookName string

// Values of HookName.
const (
	HookNameHTTPTransportPreAuthHook     HookName = "HTTPTransportPreAuthHook"
	HookNameHTTPTransportPreHook         HookName = "HTTPTransportPreHook"
	HookNameHTTPTransportPostHook        HookName = "HTTPTransportPostHook"
	HookNameHTTPTransportStreamChunkHook HookName = "HTTPTransportStreamChunkHook"
	HookNamePreRequestHook               HookName = "PreRequestHook"
	HookNamePreLLMHook                   HookName = "PreLLMHook"
	HookNamePostLLMHook                  HookName = "PostLLMHook"
	HookNamePreMCPHook                   HookName = "PreMCPHook"
	HookNamePostMCPHook                  HookName = "PostMCPHook"
	HookNamePreMCPConnectionHook         HookName = "PreMCPConnectionHook"
	HookNamePostMCPConnectionHook        HookName = "PostMCPConnectionHook"
	HookNameInject                       HookName = "Inject"
	HookNameMarshalConfigForStorage      HookName = "MarshalConfigForStorage"
	HookNameRedactConfig                 HookName = "RedactConfig"
)

// TransportErrorBody: Body of a transport-level failure (the plugin could not run the call at all)
type TransportErrorBody struct {
	Error string `json:"error"`
}

// CapabilitiesRequest: Empty request
type CapabilitiesRequest struct{}

// CapabilitiesResponse: Which hooks the plugin implements and its protocol version
type CapabilitiesResponse struct {
	// Implemented hooks; the host never calls a hook that is not listed
	Hooks []HookName `json:"hooks"`
	// Wire protocol version; the host refuses anything but the version it speaks (currently 1)
	ProtocolVersion int32 `json:"protocol_version"`
	// True when the plugin serves HookStream
	StreamSupported bool `json:"stream_supported,omitempty"`
}

// InitRequest: Plugin configuration, passed once after Capabilities
type InitRequest struct {
	Config ConfigMap `json:"config,omitempty"`
}

// InitResponse is a message of the document.
type InitResponse struct {
	Error *HookError `json:"error,omitempty"`
}

// GetNameRequest: Empty request
type GetNameRequest struct{}

// GetNameResponse is a message of the document.
type GetNameResponse struct {
	// The plugin's system identifier
	Name string `json:"name"`
}

// CleanupRequest: Empty request; sent once before the host stops the plugin process
type CleanupRequest struct{}

// CleanupResponse is a message of the document.
type CleanupResponse struct {
	Error *HookError `json:"error,omitempty"`
}

// HealthResponse: Mirrors Meridian's /health; 200 for ok/degraded, 503 for unavailable
type HealthResponse struct {
	Status string `json:"status"`
	// Component name → "ok" or a reason
	Components map[string]string `json:"components,omitempty"`
}

// StatusResponse: Identity, capabilities and counters of the plugin process
type StatusResponse struct {
	Name string `json:"name"`
	// Build version of the plugin, free-form
	Version         string       `json:"version,omitempty"`
	ProtocolVersion int32        `json:"protocol_version"`
	Hooks           []HookName   `json:"hooks"`
	StreamSupported bool         `json:"stream_supported,omitempty"`
	StartedAt       string       `json:"started_at,omitempty"`
	UptimeSeconds   int64        `json:"uptime_seconds,omitempty"`
	Stats           *StatusStats `json:"stats,omitempty"`
}

// StatusStats is a message of the document.
type StatusStats struct {
	CallsTotal  int64 `json:"calls_total,omitempty"`
	ErrorsTotal int64 `json:"errors_total,omitempty"`
	OpenStreams int32 `json:"open_streams,omitempty"`
}

// HTTPTransportPreHookRequest: Input of HTTPTransportPreAuthHook and HTTPTransportPreHook
type HTTPTransportPreHookRequest struct {
	Ctx     *ContextDetails `json:"ctx"`
	Request *RequestDetails `json:"request"`
}

// HTTPTransportPreHookResponse: Output of the transport pre-hooks. `response` set = short-circuit
// with that response; `request` echoes the (possibly mutated) request so the host can apply
// in-place semantics; `ctx` carries context writes; `error` is the hook's Go error.
type HTTPTransportPreHookResponse struct {
	Response *ResponseDetails `json:"response,omitempty"`
	Error    *HookError       `json:"error,omitempty"`
	Ctx      *ContextDelta    `json:"ctx,omitempty"`
	Request  *RequestDetails  `json:"request,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// HTTPTransportPostHookRequest is a message of the document.
type HTTPTransportPostHookRequest struct {
	Ctx      *ContextDetails  `json:"ctx"`
	Request  *RequestDetails  `json:"request"`
	Response *ResponseDetails `json:"response"`
}

// HTTPTransportPostHookResponse is a message of the document.
type HTTPTransportPostHookResponse struct {
	Error *HookError    `json:"error,omitempty"`
	Ctx   *ContextDelta `json:"ctx,omitempty"`
	// The (possibly mutated) response echoed back
	Response *ResponseDetails `json:"response,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// HTTPTransportStreamChunkHookRequest is a message of the document.
type HTTPTransportStreamChunkHookRequest struct {
	Ctx     *ContextDetails `json:"ctx"`
	Request *RequestDetails `json:"request"`
	Chunk   *StreamChunk    `json:"chunk"`
}

// HTTPTransportStreamChunkHookResponse is a message of the document.
type HTTPTransportStreamChunkHookResponse struct {
	// The (possibly mutated) chunk; absent with body_changed=true = drop the chunk
	Chunk *StreamChunk  `json:"chunk,omitempty"`
	Error *HookError    `json:"error,omitempty"`
	Ctx   *ContextDelta `json:"ctx,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PreRequestHookRequest is a message of the document.
type PreRequestHookRequest struct {
	Ctx     *ContextDetails `json:"ctx"`
	Request *LLMRequest     `json:"request"`
}

// PreRequestHookResponse: PreRequestHook cannot short-circuit; its error is non-blocking (logged
// by the host)
type PreRequestHookResponse struct {
	Error   *HookError    `json:"error,omitempty"`
	Ctx     *ContextDelta `json:"ctx,omitempty"`
	Request *LLMRequest   `json:"request,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PreLLMHookRequest is a message of the document.
type PreLLMHookRequest struct {
	Ctx     *ContextDetails `json:"ctx"`
	Request *LLMRequest     `json:"request"`
}

// PreLLMHookResponse: `request` is the (possibly mutated) request, applied only when
// `body_changed` is true. `short_circuit` stops the pipeline with a response or an error.
type PreLLMHookResponse struct {
	Request      *LLMRequest      `json:"request,omitempty"`
	ShortCircuit *LLMShortCircuit `json:"short_circuit,omitempty"`
	Error        *HookError       `json:"error,omitempty"`
	Ctx          *ContextDelta    `json:"ctx,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PostLLMHookRequest: Post-hooks receive the provider response and/or the provider error; no
// request (the LLMPlugin signature)
type PostLLMHookRequest struct {
	Ctx      *ContextDetails `json:"ctx"`
	Response *LLMResponse    `json:"response,omitempty"`
	Error    *BifrostError   `json:"error,omitempty"`
}

// PostLLMHookResponse: With body_changed=true BOTH response and plugin_error replace the host's
// (absent = nil, i.e. a recovered error)
type PostLLMHookResponse struct {
	Response *LLMResponse `json:"response,omitempty"`
	// The (possibly replaced) provider error
	PluginError *BifrostError `json:"plugin_error,omitempty"`
	Error       *HookError    `json:"error,omitempty"`
	Ctx         *ContextDelta `json:"ctx,omitempty"`
	// false (or absent): the host keeps the request/response/error/chunk it already holds and does not
	// decode any payload carried by this reply; omit the payload to save bytes. true: the payload
	// properties of this reply replace the host's objects in place; an absent property then means nil
	// (empty body, recovered error, dropped chunk). Transport metadata of an echoed request/response
	// (method, path, headers, query, path_params, status_code) is applied whenever the echo object is
	// present, independent of this flag.
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PreMCPHookRequest is a message of the document.
type PreMCPHookRequest struct {
	Ctx     *ContextDetails `json:"ctx"`
	Request *MCPRequest     `json:"request"`
}

// PreMCPHookResponse is a message of the document.
type PreMCPHookResponse struct {
	Request      *MCPRequest      `json:"request,omitempty"`
	ShortCircuit *MCPShortCircuit `json:"short_circuit,omitempty"`
	Error        *HookError       `json:"error,omitempty"`
	Ctx          *ContextDelta    `json:"ctx,omitempty"`
	// false = keep the host's request (payload not decoded); true = `request` replaces it
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PostMCPHookRequest is a message of the document.
type PostMCPHookRequest struct {
	Ctx      *ContextDetails `json:"ctx"`
	Response *MCPResponse    `json:"response,omitempty"`
	Error    *BifrostError   `json:"error,omitempty"`
}

// PostMCPHookResponse is a message of the document.
type PostMCPHookResponse struct {
	Response    *MCPResponse  `json:"response,omitempty"`
	PluginError *BifrostError `json:"plugin_error,omitempty"`
	Error       *HookError    `json:"error,omitempty"`
	Ctx         *ContextDelta `json:"ctx,omitempty"`
	// false = keep the host's response and error; true = both are replaced by this reply (absent =
	// nil)
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PreMCPConnectionHookRequest is a message of the document.
type PreMCPConnectionHookRequest struct {
	Ctx     *ContextDetails    `json:"ctx"`
	Request *MCPConnectRequest `json:"request"`
}

// PreMCPConnectionHookResponse is a message of the document.
type PreMCPConnectionHookResponse struct {
	Request      *MCPConnectRequest `json:"request,omitempty"`
	ShortCircuit *MCPShortCircuit   `json:"short_circuit,omitempty"`
	Error        *HookError         `json:"error,omitempty"`
	Ctx          *ContextDelta      `json:"ctx,omitempty"`
	// false = keep the host's request; true = the mutable fields (connection_string, headers) are
	// replaced
	BodyChanged bool `json:"body_changed,omitempty"`
}

// PostMCPConnectionHookRequest is a message of the document.
type PostMCPConnectionHookRequest struct {
	Ctx      *ContextDetails     `json:"ctx"`
	Response *MCPConnectResponse `json:"response,omitempty"`
	Error    *BifrostError       `json:"error,omitempty"`
}

// PostMCPConnectionHookResponse is a message of the document.
type PostMCPConnectionHookResponse struct {
	Response    *MCPConnectResponse `json:"response,omitempty"`
	PluginError *BifrostError       `json:"plugin_error,omitempty"`
	Error       *HookError          `json:"error,omitempty"`
	Ctx         *ContextDelta       `json:"ctx,omitempty"`
	// false = keep the host's response and error; true = both are replaced by this reply (absent =
	// nil)
	BodyChanged bool `json:"body_changed,omitempty"`
}

// InjectRequest: A completed trace. `ctx` carries only request id and deadline (Inject takes a
// plain context)
type InjectRequest struct {
	Ctx   *ContextDetails `json:"ctx"`
	Trace *Trace          `json:"trace"`
}

// InjectResponse is a message of the document.
type InjectResponse struct {
	Error *HookError `json:"error,omitempty"`
}

// ConfigMapRequest is a message of the document.
type ConfigMapRequest struct {
	Config ConfigMap `json:"config,omitempty"`
}

// ConfigMapResponse is a message of the document.
type ConfigMapResponse struct {
	Config ConfigMap  `json:"config,omitempty"`
	Error  *HookError `json:"error,omitempty"`
}

// HookStreamRequest: One host -> plugin message on the stream. `id` is echoed in the reply.
// Exactly one payload property is present and `call` names it. The lifecycle calls use the same
// envelope.
type HookStreamRequest struct {
	// Per-stream sequence number, unique among in-flight requests on this stream
	ID int64 `json:"id"`
	// Name of the call carried in this message
	Call                         string                               `json:"call"`
	Capabilities                 *CapabilitiesRequest                 `json:"capabilities,omitempty"`
	Init                         *InitRequest                         `json:"init,omitempty"`
	GetName                      *GetNameRequest                      `json:"get_name,omitempty"`
	Cleanup                      *CleanupRequest                      `json:"cleanup,omitempty"`
	HTTPTransportPreAuthHook     *HTTPTransportPreHookRequest         `json:"http_transport_pre_auth_hook,omitempty"`
	HTTPTransportPreHook         *HTTPTransportPreHookRequest         `json:"http_transport_pre_hook,omitempty"`
	HTTPTransportPostHook        *HTTPTransportPostHookRequest        `json:"http_transport_post_hook,omitempty"`
	HTTPTransportStreamChunkHook *HTTPTransportStreamChunkHookRequest `json:"http_transport_stream_chunk_hook,omitempty"`
	PreRequestHook               *PreRequestHookRequest               `json:"pre_request_hook,omitempty"`
	PreLLMHook                   *PreLLMHookRequest                   `json:"pre_llm_hook,omitempty"`
	PostLLMHook                  *PostLLMHookRequest                  `json:"post_llm_hook,omitempty"`
	PreMCPHook                   *PreMCPHookRequest                   `json:"pre_mcp_hook,omitempty"`
	PostMCPHook                  *PostMCPHookRequest                  `json:"post_mcp_hook,omitempty"`
	PreMCPConnectionHook         *PreMCPConnectionHookRequest         `json:"pre_mcp_connection_hook,omitempty"`
	PostMCPConnectionHook        *PostMCPConnectionHookRequest        `json:"post_mcp_connection_hook,omitempty"`
	Inject                       *InjectRequest                       `json:"inject,omitempty"`
	MarshalConfigForStorage      *ConfigMapRequest                    `json:"marshal_config_for_storage,omitempty"`
	RedactConfig                 *ConfigMapRequest                    `json:"redact_config,omitempty"`
}

// HookStreamResponse: One plugin -> host message. `id` matches the request. Either exactly one
// payload property is present (the call's response message) or `transport_error` explains why the
// call could not be dispatched at all (unknown call, decode failure, plugin shutting down).
type HookStreamResponse struct {
	ID int64 `json:"id"`
	// Name of the call this message answers (informational)
	Call                         string                                `json:"call,omitempty"`
	TransportError               string                                `json:"transport_error,omitempty"`
	Capabilities                 *CapabilitiesResponse                 `json:"capabilities,omitempty"`
	Init                         *InitResponse                         `json:"init,omitempty"`
	GetName                      *GetNameResponse                      `json:"get_name,omitempty"`
	Cleanup                      *CleanupResponse                      `json:"cleanup,omitempty"`
	HTTPTransportPreAuthHook     *HTTPTransportPreHookResponse         `json:"http_transport_pre_auth_hook,omitempty"`
	HTTPTransportPreHook         *HTTPTransportPreHookResponse         `json:"http_transport_pre_hook,omitempty"`
	HTTPTransportPostHook        *HTTPTransportPostHookResponse        `json:"http_transport_post_hook,omitempty"`
	HTTPTransportStreamChunkHook *HTTPTransportStreamChunkHookResponse `json:"http_transport_stream_chunk_hook,omitempty"`
	PreRequestHook               *PreRequestHookResponse               `json:"pre_request_hook,omitempty"`
	PreLLMHook                   *PreLLMHookResponse                   `json:"pre_llm_hook,omitempty"`
	PostLLMHook                  *PostLLMHookResponse                  `json:"post_llm_hook,omitempty"`
	PreMCPHook                   *PreMCPHookResponse                   `json:"pre_mcp_hook,omitempty"`
	PostMCPHook                  *PostMCPHookResponse                  `json:"post_mcp_hook,omitempty"`
	PreMCPConnectionHook         *PreMCPConnectionHookResponse         `json:"pre_mcp_connection_hook,omitempty"`
	PostMCPConnectionHook        *PostMCPConnectionHookResponse        `json:"post_mcp_connection_hook,omitempty"`
	Inject                       *InjectResponse                       `json:"inject,omitempty"`
	MarshalConfigForStorage      *ConfigMapResponse                    `json:"marshal_config_for_storage,omitempty"`
	RedactConfig                 *ConfigMapResponse                    `json:"redact_config,omitempty"`
}

// Values of the "status" property.
const (
	StatusOk          = "ok"
	StatusDegraded    = "degraded"
	StatusUnavailable = "unavailable"
)

// Values of the "call" property.
const (
	CallCapabilities                 = "Capabilities"
	CallInit                         = "Init"
	CallGetName                      = "GetName"
	CallCleanup                      = "Cleanup"
	CallHTTPTransportPreAuthHook     = "HTTPTransportPreAuthHook"
	CallHTTPTransportPreHook         = "HTTPTransportPreHook"
	CallHTTPTransportPostHook        = "HTTPTransportPostHook"
	CallHTTPTransportStreamChunkHook = "HTTPTransportStreamChunkHook"
	CallPreRequestHook               = "PreRequestHook"
	CallPreLLMHook                   = "PreLLMHook"
	CallPostLLMHook                  = "PostLLMHook"
	CallPreMCPHook                   = "PreMCPHook"
	CallPostMCPHook                  = "PostMCPHook"
	CallPreMCPConnectionHook         = "PreMCPConnectionHook"
	CallPostMCPConnectionHook        = "PostMCPConnectionHook"
	CallInject                       = "Inject"
	CallMarshalConfigForStorage      = "MarshalConfigForStorage"
	CallRedactConfig                 = "RedactConfig"
)

// BasePath is the path prefix shared by every operation.
const BasePath = "/api/meridian/plugin/v1"

// Operation is one operation of the document.
type Operation struct {
	Method         string // operationId
	Path           string
	HTTPMethod     string
	RequestSchema  string // component schema of the JSON request body, "" when none
	ResponseSchema string // component schema of the 200 JSON response, "" when none
}

// Operations lists every operation in document order.
var Operations = []Operation{
	{
		Method:         "Capabilities",
		Path:           "/api/meridian/plugin/v1/capabilities",
		HTTPMethod:     "POST",
		RequestSchema:  "CapabilitiesRequest",
		ResponseSchema: "CapabilitiesResponse",
	},
	{
		Method:         "Init",
		Path:           "/api/meridian/plugin/v1/init",
		HTTPMethod:     "POST",
		RequestSchema:  "InitRequest",
		ResponseSchema: "InitResponse",
	},
	{
		Method:         "GetName",
		Path:           "/api/meridian/plugin/v1/getname",
		HTTPMethod:     "POST",
		RequestSchema:  "GetNameRequest",
		ResponseSchema: "GetNameResponse",
	},
	{
		Method:         "Cleanup",
		Path:           "/api/meridian/plugin/v1/cleanup",
		HTTPMethod:     "POST",
		RequestSchema:  "CleanupRequest",
		ResponseSchema: "CleanupResponse",
	},
	{
		Method:         "Health",
		Path:           "/api/meridian/plugin/v1/health",
		HTTPMethod:     "GET",
		RequestSchema:  "",
		ResponseSchema: "HealthResponse",
	},
	{
		Method:         "Status",
		Path:           "/api/meridian/plugin/v1/status",
		HTTPMethod:     "GET",
		RequestSchema:  "",
		ResponseSchema: "StatusResponse",
	},
	{
		Method:         "HTTPTransportPreAuthHook",
		Path:           "/api/meridian/plugin/v1/httptransportpreauthhook",
		HTTPMethod:     "POST",
		RequestSchema:  "HTTPTransportPreHookRequest",
		ResponseSchema: "HTTPTransportPreHookResponse",
	},
	{
		Method:         "HTTPTransportPreHook",
		Path:           "/api/meridian/plugin/v1/httptransportprehook",
		HTTPMethod:     "POST",
		RequestSchema:  "HTTPTransportPreHookRequest",
		ResponseSchema: "HTTPTransportPreHookResponse",
	},
	{
		Method:         "HTTPTransportPostHook",
		Path:           "/api/meridian/plugin/v1/httptransportposthook",
		HTTPMethod:     "POST",
		RequestSchema:  "HTTPTransportPostHookRequest",
		ResponseSchema: "HTTPTransportPostHookResponse",
	},
	{
		Method:         "HTTPTransportStreamChunkHook",
		Path:           "/api/meridian/plugin/v1/httptransportstreamchunkhook",
		HTTPMethod:     "POST",
		RequestSchema:  "HTTPTransportStreamChunkHookRequest",
		ResponseSchema: "HTTPTransportStreamChunkHookResponse",
	},
	{
		Method:         "PreRequestHook",
		Path:           "/api/meridian/plugin/v1/prerequesthook",
		HTTPMethod:     "POST",
		RequestSchema:  "PreRequestHookRequest",
		ResponseSchema: "PreRequestHookResponse",
	},
	{
		Method:         "PreLLMHook",
		Path:           "/api/meridian/plugin/v1/prellmhook",
		HTTPMethod:     "POST",
		RequestSchema:  "PreLLMHookRequest",
		ResponseSchema: "PreLLMHookResponse",
	},
	{
		Method:         "PostLLMHook",
		Path:           "/api/meridian/plugin/v1/postllmhook",
		HTTPMethod:     "POST",
		RequestSchema:  "PostLLMHookRequest",
		ResponseSchema: "PostLLMHookResponse",
	},
	{
		Method:         "PreMCPHook",
		Path:           "/api/meridian/plugin/v1/premcphook",
		HTTPMethod:     "POST",
		RequestSchema:  "PreMCPHookRequest",
		ResponseSchema: "PreMCPHookResponse",
	},
	{
		Method:         "PostMCPHook",
		Path:           "/api/meridian/plugin/v1/postmcphook",
		HTTPMethod:     "POST",
		RequestSchema:  "PostMCPHookRequest",
		ResponseSchema: "PostMCPHookResponse",
	},
	{
		Method:         "PreMCPConnectionHook",
		Path:           "/api/meridian/plugin/v1/premcpconnectionhook",
		HTTPMethod:     "POST",
		RequestSchema:  "PreMCPConnectionHookRequest",
		ResponseSchema: "PreMCPConnectionHookResponse",
	},
	{
		Method:         "PostMCPConnectionHook",
		Path:           "/api/meridian/plugin/v1/postmcpconnectionhook",
		HTTPMethod:     "POST",
		RequestSchema:  "PostMCPConnectionHookRequest",
		ResponseSchema: "PostMCPConnectionHookResponse",
	},
	{
		Method:         "Inject",
		Path:           "/api/meridian/plugin/v1/inject",
		HTTPMethod:     "POST",
		RequestSchema:  "InjectRequest",
		ResponseSchema: "InjectResponse",
	},
	{
		Method:         "MarshalConfigForStorage",
		Path:           "/api/meridian/plugin/v1/marshalconfigforstorage",
		HTTPMethod:     "POST",
		RequestSchema:  "ConfigMapRequest",
		ResponseSchema: "ConfigMapResponse",
	},
	{
		Method:         "RedactConfig",
		Path:           "/api/meridian/plugin/v1/redactconfig",
		HTTPMethod:     "POST",
		RequestSchema:  "ConfigMapRequest",
		ResponseSchema: "ConfigMapResponse",
	},
	{
		Method:         "HookStream",
		Path:           "/api/meridian/plugin/v1/hookstream",
		HTTPMethod:     "GET",
		RequestSchema:  "",
		ResponseSchema: "",
	},
}
